backend:
  name: "git-gateway"
  branch: "main"

media_folder: "public/images"
public_folder: "/public/images"  

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date Published", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }